export interface MinariDataset {
  id: string
  namespace: string
  envName: string
  datasetName: string
  version: number
  totalEpisodes: number
  totalSteps: number
  actionSpaceType: string
  actionSpaceDims: number
  observationSpaceType: string
  observationSpaceDims: number
  algorithmName: string
  author: string
  minariVersion: string
  description: string
  tags: string[]
  episodeStats: EpisodeStats
  downloads: number
  createdAt: string
}

export interface EpisodeStats {
  rewardsMean: number
  rewardsStd: number
  rewardsMin: number
  rewardsMax: number
  avgEpisodeLength: number
  rewardDistribution: { bin: string; count: number }[]
  episodeLengthDistribution: { bin: string; count: number }[]
  cumulativeRewards: { episode: number; reward: number }[]
}

// Illustrative catalog data, not measurements from downloaded episodes.
// Keep generated examples deterministic across server and browser rendering.
function generateRewardDistribution(mean: number, std: number, min: number, max: number): { bin: string; count: number }[] {
  const bins = 12
  const range = max - min
  const binWidth = range / bins
  return Array.from({ length: bins }, (_, i) => {
    const binStart = min + i * binWidth
    const binCenter = binStart + binWidth / 2
    const z = (binCenter - mean) / (std || 1)
    const density = Math.exp(-0.5 * z * z)
    return {
      bin: binStart.toFixed(1),
      count: Math.max(1, Math.round(density * 100)),
    }
  })
}

function generateEpisodeLengthDistribution(avgLen: number): { bin: string; count: number }[] {
  const bins = 10
  const minLen = Math.max(1, Math.round(avgLen * 0.2))
  const maxLen = Math.round(avgLen * 2.2)
  const binWidth = (maxLen - minLen) / bins
  return Array.from({ length: bins }, (_, i) => {
    const binStart = minLen + i * binWidth
    const binCenter = binStart + binWidth / 2
    const z = (binCenter - avgLen) / (avgLen * 0.35)
    const density = Math.exp(-0.5 * z * z)
    return {
      bin: Math.round(binStart).toString(),
      count: Math.max(1, Math.round(density * 80)),
    }
  })
}

function generateCumulativeRewards(numEpisodes: number, mean: number, std: number): { episode: number; reward: number }[] {
  const sampleSize = Math.min(numEpisodes, 50)
  const step = Math.max(1, Math.floor(numEpisodes / sampleSize))
  return Array.from({ length: sampleSize }, (_, i) => ({
    episode: i * step,
    reward: parseFloat((mean + Math.sin(i * 1.7) * std).toFixed(2)),
  }))
}

function makeStats(
  mean: number,
  std: number,
  min: number,
  max: number,
  avgLen: number,
  episodes: number
): EpisodeStats {
  return {
    rewardsMean: mean,
    rewardsStd: std,
    rewardsMin: min,
    rewardsMax: max,
    avgEpisodeLength: avgLen,
    rewardDistribution: generateRewardDistribution(mean, std, min, max),
    episodeLengthDistribution: generateEpisodeLengthDistribution(avgLen),
    cumulativeRewards: generateCumulativeRewards(episodes, mean, std),
  }
}

export const MINARI_DATASETS: MinariDataset[] = [
  // D4RL - Point Maze
  {
    id: "D4RL/pointmaze/umaze-v2",
    namespace: "D4RL",
    envName: "Point Maze",
    datasetName: "Umaze",
    version: 2,
    totalEpisodes: 1267,
    totalSteps: 305281,
    actionSpaceType: "Box",
    actionSpaceDims: 2,
    observationSpaceType: "Dict",
    observationSpaceDims: 6,
    algorithmName: "Waypoint Controller",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Point maze navigation in a U-shaped maze using a waypoint controller policy.",
    tags: ["D4RL", "Maze", "Navigation", "Continuous"],
    episodeStats: makeStats(82.4, 35.2, 0.0, 158.3, 241, 1267),
    downloads: 4895,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/pointmaze/medium-v2",
    namespace: "D4RL",
    envName: "Point Maze",
    datasetName: "Medium",
    version: 2,
    totalEpisodes: 2004,
    totalSteps: 999982,
    actionSpaceType: "Box",
    actionSpaceDims: 2,
    observationSpaceType: "Dict",
    observationSpaceDims: 6,
    algorithmName: "Waypoint Controller",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Point maze navigation in a medium-difficulty maze layout with complex paths.",
    tags: ["D4RL", "Maze", "Navigation", "Continuous"],
    episodeStats: makeStats(64.1, 42.8, -12.0, 192.5, 499, 2004),
    downloads: 3210,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/pointmaze/large-v2",
    namespace: "D4RL",
    envName: "Point Maze",
    datasetName: "Large",
    version: 2,
    totalEpisodes: 4097,
    totalSteps: 3995934,
    actionSpaceType: "Box",
    actionSpaceDims: 2,
    observationSpaceType: "Dict",
    observationSpaceDims: 6,
    algorithmName: "Waypoint Controller",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Point maze navigation in a large maze with lengthy trajectories and sparse rewards.",
    tags: ["D4RL", "Maze", "Navigation", "Continuous"],
    episodeStats: makeStats(48.7, 55.1, -25.0, 280.0, 975, 4097),
    downloads: 2780,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/pointmaze/open-v2",
    namespace: "D4RL",
    envName: "Point Maze",
    datasetName: "Open",
    version: 2,
    totalEpisodes: 1187,
    totalSteps: 248105,
    actionSpaceType: "Box",
    actionSpaceDims: 2,
    observationSpaceType: "Dict",
    observationSpaceDims: 6,
    algorithmName: "Waypoint Controller",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Point maze in an open environment with minimal obstacles.",
    tags: ["D4RL", "Maze", "Navigation", "Continuous"],
    episodeStats: makeStats(95.3, 22.1, 15.0, 132.0, 209, 1187),
    downloads: 1950,
    createdAt: "2024-11-05",
  },
  // D4RL - Ant Maze
  {
    id: "D4RL/antmaze/umaze-v2",
    namespace: "D4RL",
    envName: "Ant Maze",
    datasetName: "Umaze",
    version: 2,
    totalEpisodes: 1499,
    totalSteps: 999926,
    actionSpaceType: "Box",
    actionSpaceDims: 8,
    observationSpaceType: "Dict",
    observationSpaceDims: 29,
    algorithmName: "Waypoint Controller",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Ant robot navigating a U-shaped maze. High-dimensional continuous control with 8 joint actuators.",
    tags: ["D4RL", "Maze", "MuJoCo", "Locomotion"],
    episodeStats: makeStats(0.62, 0.38, 0.0, 1.0, 667, 1499),
    downloads: 4120,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/antmaze/medium-play-v2",
    namespace: "D4RL",
    envName: "Ant Maze",
    datasetName: "Medium-Play",
    version: 2,
    totalEpisodes: 2998,
    totalSteps: 1999928,
    actionSpaceType: "Box",
    actionSpaceDims: 8,
    observationSpaceType: "Dict",
    observationSpaceDims: 29,
    algorithmName: "Diverse Controller",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Ant robot exploring diverse paths in a medium maze for play-style data collection.",
    tags: ["D4RL", "Maze", "MuJoCo", "Locomotion"],
    episodeStats: makeStats(0.41, 0.42, 0.0, 1.0, 667, 2998),
    downloads: 3540,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/antmaze/large-diverse-v2",
    namespace: "D4RL",
    envName: "Ant Maze",
    datasetName: "Large-Diverse",
    version: 2,
    totalEpisodes: 3998,
    totalSteps: 3999696,
    actionSpaceType: "Box",
    actionSpaceDims: 8,
    observationSpaceType: "Dict",
    observationSpaceDims: 29,
    algorithmName: "Diverse Controller",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Ant robot in a large maze with highly diverse trajectories and challenging navigation.",
    tags: ["D4RL", "Maze", "MuJoCo", "Locomotion"],
    episodeStats: makeStats(0.28, 0.39, 0.0, 1.0, 1000, 3998),
    downloads: 2890,
    createdAt: "2024-11-05",
  },
  // D4RL - Door
  {
    id: "D4RL/door/human-v2",
    namespace: "D4RL",
    envName: "Door",
    datasetName: "Human",
    version: 2,
    totalEpisodes: 6729,
    totalSteps: 327680,
    actionSpaceType: "Box",
    actionSpaceDims: 28,
    observationSpaceType: "Box",
    observationSpaceDims: 39,
    algorithmName: "Human Teleoperation",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Robotic hand opening a door, collected via human teleoperation demonstrations.",
    tags: ["D4RL", "Adroit", "Dexterous", "Human"],
    episodeStats: makeStats(12.8, 18.5, -6.2, 82.4, 49, 6729),
    downloads: 3150,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/door/cloned-v2",
    namespace: "D4RL",
    envName: "Door",
    datasetName: "Cloned",
    version: 2,
    totalEpisodes: 8192,
    totalSteps: 491520,
    actionSpaceType: "Box",
    actionSpaceDims: 28,
    observationSpaceType: "Box",
    observationSpaceDims: 39,
    algorithmName: "Behavioral Cloning",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Robotic hand opening a door, collected from a behavioral cloning policy trained on human data.",
    tags: ["D4RL", "Adroit", "Dexterous", "Cloned"],
    episodeStats: makeStats(8.2, 15.3, -8.1, 75.2, 60, 8192),
    downloads: 2440,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/door/expert-v2",
    namespace: "D4RL",
    envName: "Door",
    datasetName: "Expert",
    version: 2,
    totalEpisodes: 5000,
    totalSteps: 250000,
    actionSpaceType: "Box",
    actionSpaceDims: 28,
    observationSpaceType: "Box",
    observationSpaceDims: 39,
    algorithmName: "RL Expert Policy",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Robotic hand opening a door, collected from an RL-trained expert policy.",
    tags: ["D4RL", "Adroit", "Dexterous", "Expert"],
    episodeStats: makeStats(52.1, 12.4, 18.0, 85.6, 50, 5000),
    downloads: 3680,
    createdAt: "2024-11-05",
  },
  // D4RL - Pen
  {
    id: "D4RL/pen/human-v2",
    namespace: "D4RL",
    envName: "Pen",
    datasetName: "Human",
    version: 2,
    totalEpisodes: 5000,
    totalSteps: 500000,
    actionSpaceType: "Box",
    actionSpaceDims: 24,
    observationSpaceType: "Box",
    observationSpaceDims: 45,
    algorithmName: "Human Teleoperation",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Dexterous pen manipulation using a Shadow Hand, collected via human teleoperation.",
    tags: ["D4RL", "Adroit", "Dexterous", "Human"],
    episodeStats: makeStats(42.5, 28.3, -10.0, 120.0, 100, 5000),
    downloads: 2750,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/pen/expert-v2",
    namespace: "D4RL",
    envName: "Pen",
    datasetName: "Expert",
    version: 2,
    totalEpisodes: 5000,
    totalSteps: 500000,
    actionSpaceType: "Box",
    actionSpaceDims: 24,
    observationSpaceType: "Box",
    observationSpaceDims: 45,
    algorithmName: "RL Expert Policy",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Dexterous pen manipulation using a Shadow Hand, expert RL policy demonstrations.",
    tags: ["D4RL", "Adroit", "Dexterous", "Expert"],
    episodeStats: makeStats(98.4, 15.2, 30.0, 140.0, 100, 5000),
    downloads: 3190,
    createdAt: "2024-11-05",
  },
  // D4RL - Hammer
  {
    id: "D4RL/hammer/human-v2",
    namespace: "D4RL",
    envName: "Hammer",
    datasetName: "Human",
    version: 2,
    totalEpisodes: 3214,
    totalSteps: 642800,
    actionSpaceType: "Box",
    actionSpaceDims: 26,
    observationSpaceType: "Box",
    observationSpaceDims: 46,
    algorithmName: "Human Teleoperation",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Robotic hand using a hammer to drive a nail, teleoperated by humans.",
    tags: ["D4RL", "Adroit", "Dexterous", "Human"],
    episodeStats: makeStats(1.2, 2.8, -3.0, 15.4, 200, 3214),
    downloads: 1890,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/hammer/expert-v2",
    namespace: "D4RL",
    envName: "Hammer",
    datasetName: "Expert",
    version: 2,
    totalEpisodes: 5000,
    totalSteps: 1000000,
    actionSpaceType: "Box",
    actionSpaceDims: 26,
    observationSpaceType: "Box",
    observationSpaceDims: 46,
    algorithmName: "RL Expert Policy",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Robotic hand using a hammer to drive a nail, collected from expert RL policy.",
    tags: ["D4RL", "Adroit", "Dexterous", "Expert"],
    episodeStats: makeStats(78.6, 22.1, 5.0, 125.0, 200, 5000),
    downloads: 2340,
    createdAt: "2024-11-05",
  },
  // D4RL - Relocate
  {
    id: "D4RL/relocate/human-v2",
    namespace: "D4RL",
    envName: "Relocate",
    datasetName: "Human",
    version: 2,
    totalEpisodes: 3467,
    totalSteps: 693400,
    actionSpaceType: "Box",
    actionSpaceDims: 30,
    observationSpaceType: "Box",
    observationSpaceDims: 39,
    algorithmName: "Human Teleoperation",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Object relocation using a dexterous robotic hand, collected from human demonstrations.",
    tags: ["D4RL", "Adroit", "Dexterous", "Human"],
    episodeStats: makeStats(-2.5, 4.1, -15.0, 8.2, 200, 3467),
    downloads: 1650,
    createdAt: "2024-11-05",
  },
  // D4RL - Kitchen
  {
    id: "D4RL/kitchen/complete-v2",
    namespace: "D4RL",
    envName: "Kitchen",
    datasetName: "Complete",
    version: 2,
    totalEpisodes: 3680,
    totalSteps: 1070440,
    actionSpaceType: "Box",
    actionSpaceDims: 9,
    observationSpaceType: "Box",
    observationSpaceDims: 60,
    algorithmName: "Human Teleoperation",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Kitchen manipulation environment with a 9-DOF Franka robot completing all subtasks.",
    tags: ["D4RL", "Kitchen", "Manipulation", "Multi-task"],
    episodeStats: makeStats(3.2, 1.1, 0.0, 4.0, 291, 3680),
    downloads: 3020,
    createdAt: "2024-11-05",
  },
  {
    id: "D4RL/kitchen/partial-v2",
    namespace: "D4RL",
    envName: "Kitchen",
    datasetName: "Partial",
    version: 2,
    totalEpisodes: 3680,
    totalSteps: 1070440,
    actionSpaceType: "Box",
    actionSpaceDims: 9,
    observationSpaceType: "Box",
    observationSpaceDims: 60,
    algorithmName: "Human Teleoperation",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "Kitchen manipulation with partial task completion demonstrations.",
    tags: ["D4RL", "Kitchen", "Manipulation", "Multi-task"],
    episodeStats: makeStats(1.8, 1.0, 0.0, 4.0, 291, 3680),
    downloads: 2560,
    createdAt: "2024-11-05",
  },
  // MiniGrid
  {
    id: "minigrid/fourrooms-v0",
    namespace: "MiniGrid",
    envName: "FourRooms",
    datasetName: "Optimal",
    version: 0,
    totalEpisodes: 10000,
    totalSteps: 380000,
    actionSpaceType: "Discrete",
    actionSpaceDims: 7,
    observationSpaceType: "Dict",
    observationSpaceDims: 147,
    algorithmName: "BFS Optimal",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "MiniGrid FourRooms environment with optimal BFS-generated trajectories.",
    tags: ["MiniGrid", "Grid", "Navigation", "Discrete"],
    episodeStats: makeStats(0.92, 0.12, 0.0, 1.0, 38, 10000),
    downloads: 4052,
    createdAt: "2024-11-19",
  },
  {
    id: "minigrid/babyai-pickup-v0",
    namespace: "MiniGrid",
    envName: "BabyAI Pickup",
    datasetName: "Optimal",
    version: 0,
    totalEpisodes: 50000,
    totalSteps: 450000,
    actionSpaceType: "Discrete",
    actionSpaceDims: 7,
    observationSpaceType: "Dict",
    observationSpaceDims: 147,
    algorithmName: "BFS Optimal",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "BabyAI Pickup task: pick up an object of a specified type and color.",
    tags: ["MiniGrid", "BabyAI", "Instruction", "Discrete"],
    episodeStats: makeStats(0.95, 0.08, 0.0, 1.0, 9, 50000),
    downloads: 1820,
    createdAt: "2024-11-19",
  },
  {
    id: "minigrid/babyai-gotobj-v0",
    namespace: "MiniGrid",
    envName: "BabyAI GoToObj",
    datasetName: "Optimal",
    version: 0,
    totalEpisodes: 50000,
    totalSteps: 300000,
    actionSpaceType: "Discrete",
    actionSpaceDims: 7,
    observationSpaceType: "Dict",
    observationSpaceDims: 147,
    algorithmName: "BFS Optimal",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "BabyAI GoToObj: Navigate to an object in a single room.",
    tags: ["MiniGrid", "BabyAI", "Instruction", "Discrete"],
    episodeStats: makeStats(0.97, 0.05, 0.0, 1.0, 6, 50000),
    downloads: 1540,
    createdAt: "2024-11-19",
  },
  {
    id: "minigrid/babyai-bosslevel-v0",
    namespace: "MiniGrid",
    envName: "BabyAI BossLevel",
    datasetName: "Optimal",
    version: 0,
    totalEpisodes: 50000,
    totalSteps: 4500000,
    actionSpaceType: "Discrete",
    actionSpaceDims: 7,
    observationSpaceType: "Dict",
    observationSpaceDims: 147,
    algorithmName: "BFS Optimal",
    author: "Farama Foundation",
    minariVersion: "0.4.3",
    description: "BabyAI BossLevel: The most challenging BabyAI task combining all skills.",
    tags: ["MiniGrid", "BabyAI", "Instruction", "Discrete"],
    episodeStats: makeStats(0.68, 0.35, 0.0, 1.0, 90, 50000),
    downloads: 2100,
    createdAt: "2024-11-19",
  },
  // Atari
  {
    id: "atari/breakout/expert-v0",
    namespace: "Atari",
    envName: "Breakout",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 100,
    totalSteps: 458320,
    actionSpaceType: "Discrete",
    actionSpaceDims: 4,
    observationSpaceType: "Box",
    observationSpaceDims: 84,
    algorithmName: "CleanRL PPO",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "Atari Breakout played by a CleanRL PPO-trained expert agent.",
    tags: ["Atari", "Arcade", "Expert", "Discrete"],
    episodeStats: makeStats(312.5, 89.2, 42.0, 520.0, 4583, 100),
    downloads: 3976,
    createdAt: "2025-03-22",
  },
  {
    id: "atari/pong/expert-v0",
    namespace: "Atari",
    envName: "Pong",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 100,
    totalSteps: 125000,
    actionSpaceType: "Discrete",
    actionSpaceDims: 6,
    observationSpaceType: "Box",
    observationSpaceDims: 84,
    algorithmName: "CleanRL PPO",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "Atari Pong played by a CleanRL PPO-trained expert agent.",
    tags: ["Atari", "Arcade", "Expert", "Discrete"],
    episodeStats: makeStats(19.8, 1.5, 14.0, 21.0, 1250, 100),
    downloads: 2840,
    createdAt: "2025-03-22",
  },
  {
    id: "atari/spaceinvaders/expert-v0",
    namespace: "Atari",
    envName: "Space Invaders",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 100,
    totalSteps: 210500,
    actionSpaceType: "Discrete",
    actionSpaceDims: 6,
    observationSpaceType: "Box",
    observationSpaceDims: 84,
    algorithmName: "CleanRL PPO",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "Atari Space Invaders played by expert PPO policy from CleanRL.",
    tags: ["Atari", "Arcade", "Expert", "Discrete"],
    episodeStats: makeStats(1285.0, 420.0, 280.0, 2450.0, 2105, 100),
    downloads: 2210,
    createdAt: "2025-03-22",
  },
  {
    id: "atari/seaquest/expert-v0",
    namespace: "Atari",
    envName: "Seaquest",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 100,
    totalSteps: 380000,
    actionSpaceType: "Discrete",
    actionSpaceDims: 18,
    observationSpaceType: "Box",
    observationSpaceDims: 84,
    algorithmName: "CleanRL PPO",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "Atari Seaquest played by expert PPO policy.",
    tags: ["Atari", "Arcade", "Expert", "Discrete"],
    episodeStats: makeStats(2450.0, 850.0, 400.0, 5200.0, 3800, 100),
    downloads: 1680,
    createdAt: "2025-03-22",
  },
  {
    id: "atari/montezumarevenge/expert-v0",
    namespace: "Atari",
    envName: "Montezuma Revenge",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 100,
    totalSteps: 520000,
    actionSpaceType: "Discrete",
    actionSpaceDims: 18,
    observationSpaceType: "Box",
    observationSpaceDims: 84,
    algorithmName: "CleanRL PPO",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "Atari Montezuma's Revenge - notoriously hard exploration game with sparse rewards.",
    tags: ["Atari", "Arcade", "Expert", "Discrete", "Sparse"],
    episodeStats: makeStats(2100.0, 1800.0, 0.0, 8500.0, 5200, 100),
    downloads: 1950,
    createdAt: "2025-03-22",
  },
  // MuJoCo
  {
    id: "mujoco/halfcheetah/expert-v0",
    namespace: "MuJoCo",
    envName: "HalfCheetah",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 1000,
    totalSteps: 1000000,
    actionSpaceType: "Box",
    actionSpaceDims: 6,
    observationSpaceType: "Box",
    observationSpaceDims: 17,
    algorithmName: "SAC Expert",
    author: "Farama Foundation",
    minariVersion: "0.5.0",
    description: "HalfCheetah locomotion from a SAC-trained expert policy.",
    tags: ["MuJoCo", "Locomotion", "Expert", "Continuous"],
    episodeStats: makeStats(11200.0, 1500.0, 5400.0, 14800.0, 1000, 1000),
    downloads: 4641,
    createdAt: "2024-11-06",
  },
  {
    id: "mujoco/hopper/expert-v0",
    namespace: "MuJoCo",
    envName: "Hopper",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 1000,
    totalSteps: 1000000,
    actionSpaceType: "Box",
    actionSpaceDims: 3,
    observationSpaceType: "Box",
    observationSpaceDims: 11,
    algorithmName: "SAC Expert",
    author: "Farama Foundation",
    minariVersion: "0.5.0",
    description: "Hopper single-leg locomotion from a SAC-trained expert.",
    tags: ["MuJoCo", "Locomotion", "Expert", "Continuous"],
    episodeStats: makeStats(3420.0, 280.0, 1800.0, 3780.0, 1000, 1000),
    downloads: 3890,
    createdAt: "2024-11-06",
  },
  {
    id: "mujoco/walker2d/expert-v0",
    namespace: "MuJoCo",
    envName: "Walker2d",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 1000,
    totalSteps: 1000000,
    actionSpaceType: "Box",
    actionSpaceDims: 6,
    observationSpaceType: "Box",
    observationSpaceDims: 17,
    algorithmName: "SAC Expert",
    author: "Farama Foundation",
    minariVersion: "0.5.0",
    description: "Walker2d bipedal locomotion from an SAC-trained expert policy.",
    tags: ["MuJoCo", "Locomotion", "Expert", "Continuous"],
    episodeStats: makeStats(4850.0, 420.0, 2200.0, 5500.0, 1000, 1000),
    downloads: 3240,
    createdAt: "2024-11-06",
  },
  {
    id: "mujoco/ant/expert-v0",
    namespace: "MuJoCo",
    envName: "Ant",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 1000,
    totalSteps: 1000000,
    actionSpaceType: "Box",
    actionSpaceDims: 8,
    observationSpaceType: "Box",
    observationSpaceDims: 27,
    algorithmName: "SAC Expert",
    author: "Farama Foundation",
    minariVersion: "0.5.0",
    description: "Ant quadruped locomotion from a SAC-trained expert policy.",
    tags: ["MuJoCo", "Locomotion", "Expert", "Continuous"],
    episodeStats: makeStats(5820.0, 680.0, 2800.0, 7200.0, 1000, 1000),
    downloads: 2960,
    createdAt: "2024-11-06",
  },
  // MetaWorld
  {
    id: "metaworld/button-press-v2",
    namespace: "MetaWorld",
    envName: "Button Press",
    datasetName: "Expert",
    version: 2,
    totalEpisodes: 2500,
    totalSteps: 375000,
    actionSpaceType: "Box",
    actionSpaceDims: 4,
    observationSpaceType: "Box",
    observationSpaceDims: 39,
    algorithmName: "SAC Expert",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "MetaWorld button pressing task with a Sawyer robot arm.",
    tags: ["MetaWorld", "Manipulation", "Expert", "Continuous"],
    episodeStats: makeStats(4200.0, 350.0, 2800.0, 4800.0, 150, 2500),
    downloads: 3393,
    createdAt: "2025-05-07",
  },
  {
    id: "metaworld/drawer-open-v2",
    namespace: "MetaWorld",
    envName: "Drawer Open",
    datasetName: "Expert",
    version: 2,
    totalEpisodes: 2500,
    totalSteps: 375000,
    actionSpaceType: "Box",
    actionSpaceDims: 4,
    observationSpaceType: "Box",
    observationSpaceDims: 39,
    algorithmName: "SAC Expert",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "MetaWorld drawer opening task with a Sawyer robot arm.",
    tags: ["MetaWorld", "Manipulation", "Expert", "Continuous"],
    episodeStats: makeStats(3800.0, 420.0, 2100.0, 4600.0, 150, 2500),
    downloads: 2180,
    createdAt: "2025-05-07",
  },
  {
    id: "metaworld/pick-place-v2",
    namespace: "MetaWorld",
    envName: "Pick Place",
    datasetName: "Expert",
    version: 2,
    totalEpisodes: 2500,
    totalSteps: 375000,
    actionSpaceType: "Box",
    actionSpaceDims: 4,
    observationSpaceType: "Box",
    observationSpaceDims: 39,
    algorithmName: "SAC Expert",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "MetaWorld pick and place manipulation task with a Sawyer robot arm.",
    tags: ["MetaWorld", "Manipulation", "Expert", "Continuous"],
    episodeStats: makeStats(3200.0, 580.0, 1500.0, 4400.0, 150, 2500),
    downloads: 2540,
    createdAt: "2025-05-07",
  },
  // WebAgents
  {
    id: "webagents/webarena-v0",
    namespace: "WebAgents",
    envName: "WebArena",
    datasetName: "Expert",
    version: 0,
    totalEpisodes: 812,
    totalSteps: 8950,
    actionSpaceType: "Text",
    actionSpaceDims: 0,
    observationSpaceType: "Dict",
    observationSpaceDims: 0,
    algorithmName: "Human Demonstrations",
    author: "Farama Foundation",
    minariVersion: "0.5.3",
    description: "WebArena web navigation tasks with human expert demonstrations.",
    tags: ["WebAgents", "Web", "NLP", "Multimodal"],
    episodeStats: makeStats(0.42, 0.38, 0.0, 1.0, 11, 812),
    downloads: 2077,
    createdAt: "2025-05-15",
  },
]

export const NAMESPACES = [...new Set(MINARI_DATASETS.map(d => d.namespace))]

export const ENV_NAMES = [...new Set(MINARI_DATASETS.map(d => d.envName))]

export const ALL_TAGS = [...new Set(MINARI_DATASETS.flatMap(d => d.tags))].sort()

export function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`
  return n.toString()
}
